version: 2.1

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
  test:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: cd deployment && sh deploylocal.sh
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run -s "cypress/integration/test_basic.js"
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  testBackend:
    docker:
        - image: rocker/shiny-verse:4.0.1
    steps:
      - checkout
      - run: echo "Hello world!"
      - run: cp deployment/requirements.R iGOEGGO_r_shiny/
      - run: |
          # library("remotes")
          # R -e "remotes::install_github(\"r-lib/vdiffr\")"
          # R -e "install.packages(\"vdiffr\")"
          # R -e "install.packages(\"dplyr\")"
          cd iGOEGGO_r_shiny
          R -f requirements.R
      - run: | 
          cd iGOEGGO_r_shiny
          R -e "testthat::test_dir('tests')"
          #R -e "testthat::test_dir('tests')" >> test.txt
          #cat test.txt
          #grep -Fxq "FAIL 0" test.txt

  testShiny:
    docker:
        - image: rocker/shiny-verse:4.0.1
    steps:
      - checkout
      - run: echo "Hello world!"
      - run: cp deployment/requirements.R iGOEGGO_r_shiny/
      - run: cp deployment/installdipl.R iGOEGGO_r_shiny/
      - run: |
          cd iGOEGGO_r_shiny
          R -f requirements.R
          R -f installdipl.R
          R -e "install.packages(\"webshot\")"
          R -e "shinytest::installDependencies()"
      - run: | 
          cd iGOEGGO_r_shiny
          R -e "shiny::runTests()"

  testLocal:
    machine: # executor type
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: cd deployment && sh deploylocal.sh 3456
      - run: curl localhost:3456
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt-get install nodejs
      - run: npm install cypress --save-dev
      - run: ./node_modules/.bin/cypress run --config baseUrl="http://127.0.0.1:3456"

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - testLocal
